### ISSUE TITLE
Does not seem to work on Ubuntu

### ISSUE THREAD

**Issue by sebbekarlsson** [SuprDewd/NineToFive#1]
> This does not seem to work on Ubuntu

```
$ make
make: *** No targets specified and no makefile found.  Stop.
$ make install
make: *** No rule to make target `install'.  Stop.
```

**Comment by SuprDewd** [comment]
Make sure you run ./autogen.sh and ./configure first, as specified in the REAMDE. This works for me, so I believe this should fix it for you.
